library(viridis) 
library(tidyverse)
library(ggrepel)
library(shinythemes)
library(shiny)
library(dplyr)
library(readr)
library(ggplot2)
library(maps)
library(terra)
library(shinydashboard)
library(plotly)
library(rlang)
library(RColorBrewer)

GTD <- read_csv('data/globalterrorismdb.csv', col_types = readr::cols())
